<a href="https://colab.research.google.com/github/MelB18/EasyQuanten/blob/main/ErsteSchritte.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vorbereitung

Alles Notwendige installieren und importieren.

test

In [ ]:
# Install required packages.

%pip install --upgrade 'qiskit[visualization]>=2.5.0' qiskit-aer qiskit-ibm-runtime matplotlib


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 65.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 95.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 45.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 101.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.6/412.6 kB 27.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.7/120.7 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.7/94.7 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 87.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.2/224.2 kB 15.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/7

In [ ]:
import os
import platform
import shutil
import subprocess
import sys


import qiskit



from qiskit.circuit import QuantumCircuit
from qiskit.primitives import StatevectorSampler
from qiskit.quantum_info import SparsePauliOp, Statevector, Operator
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit.visualization import array_to_latex, plot_histogram, plot_state_qsphere
from qiskit_aer import AerSimulator
from qiskit_ibm_runtime import Batch, QiskitRuntimeService
from qiskit_ibm_runtime import EstimatorV2 as Estimator
from qiskit_ibm_runtime import SamplerV2 as Sampler

import matplotlib.pyplot as plt
import numpy as np


from numpy import sqrt



print(f"Qiskit version: {qiskit.__version__}")




Qiskit version: 2.5.2


# 1 Basis Wissen
## 1.0 Bits versus Qubits

Bits sind 0 oder 1 - so wie Münzen Kopf oder Zahl sind.

Wenn sie flach auf dem Tisch liegen, ist die Wahrscheinlich für Kopf oder Zahl jeweils 100% oder 0%.

Wirft man die Münze in die Luft, ist die Wahrscheinlichkeit - solange sie in der Luft ist - irgendwas dazwischen.

Zum Beispiel: 30% Kopf und 70% Zahl

Als Vektor schreibt man das so:

In [ ]:
bitVec = np.array([[0.3],[0.7]])

print("Wahrscheinlichkeitsvektor: ")
print(bitVec)

print("Schön formatiert:")

display(array_to_latex(bitVec))


Wahrscheinlichkeitsvektor: 
[[0.3]
 [0.7]]
Schön formatiert:


<IPython.core.display.Latex object>

Für einen solchen Wahrscheinlichkeitsvektor muss festgelegt werden, was oben und was unten steht.

In unserem Beispiel steht oben die Wahrscheinlich für Kopf und unten die Wahrscheinlich für Zahl.

Wichtig: Damit es ein gültiger Wahrscheinlichkeitsvektor ist, muss er zwei reele Zahlen zwischen 0 und 1 enthalten, die in Summe 1 ergeben.

In [ ]:
print("Wahrscheinlichkeit Kopf: ",bitVec[0])
print("Wahrscheinlichkeit Zahl: ",bitVec[1])
print("Summe: ",bitVec[0]+bitVec[1])


Wahrscheinlichkeit Kopf:  [0.3]
Wahrscheinlichkeit Zahl:  [0.7]
Summe:  [1.]


Für Bits ist die allgemeine Festlegung, dass oben die Wahrscheinlichkeit von 0 und unten die Wahrscheinlichkeit von 1 steht.

In [ ]:
bitZero = np.array([[1],[0]])
bitOne = np.array([[0],[1]])

print("Wahrscheinlichkeitsvektor für 100% Wert 0 (und 0% Wert 1): ")
print(bitZero)
print("Wahrscheinlichkeitsvektor für 100% Wert 1 (und 0% Wert 0): ")
print(bitOne)

Wahrscheinlichkeitsvektor für 100% Wert 0 (und 0% Wert 1): 
[[1]
 [0]]
Wahrscheinlichkeitsvektor für 100% Wert 1 (und 0% Wert 0): 
[[0]
 [1]]


## 1.2 Qubits als Vektoren

Qubits lassen ähnlich wie Bits als Vektor mit zwei Zahlen schreiben.

Es gibt jedoch zwei Hauptunterschiede:



1.   Der Vektor kann imaginären Zahlen enthalten und nicht nur  reele Zahlen
2.   Um die Wahrscheinlichkeiten zu bestimmt müssen die Zahlen quadriert werden.



In [ ]:
zero = Statevector.from_label("0")
one = Statevector.from_label("1")

print("Vektor für 100% Wert 0 (und 0% Wert 1): ")
display(zero.draw("text"))
print("Vektor für 100% Wert 1 (und 0% Wert 0): ")
display(one.draw("text"))


Vektor für 100% Wert 0 (und 0% Wert 1): 


[1.+0.j,0.+0.j]

Vektor für 100% Wert 1 (und 0% Wert 0): 


[0.+0.j,1.+0.j]

Um die Werte 1 und 0 einfach darzustellen gibt es die folgende Schreibweise

In [ ]:


print("Andere Schreibweise für 100% Wert 0: ")
display(zero.draw("latex"))
print("Andere Schreibweise für 100% Wert 1: ")
display(one.draw("latex"))

Andere Schreibweise für 100% Wert 0: 


<IPython.core.display.Latex object>

Andere Schreibweise für 100% Wert 1: 


<IPython.core.display.Latex object>