<a href="https://colab.research.google.com/github/MelB18/EasyQuanten/blob/main/ErsteSchritte.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vorbereitung

Als Erstes müssen wir verschiedene "Sachen" installieren und importieren.


In [1]:
# Install required packages.

%pip install --upgrade 'qiskit[visualization]>=2.5.0' qiskit-aer qiskit-ibm-runtime matplotlib


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 53.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 48.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 40.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 47.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.6/412.6 kB 14.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.7/120.7 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.7/95.7 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 59.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.2/224.2 kB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.9/54.9 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6

In [1]:
import os
import platform
import shutil
import subprocess
import sys


import qiskit



from qiskit.circuit import QuantumCircuit
from qiskit.primitives import StatevectorSampler
from qiskit.quantum_info import SparsePauliOp, Statevector, Operator
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit.visualization import array_to_latex, plot_histogram, plot_state_qsphere
from qiskit_aer import AerSimulator
from qiskit_ibm_runtime import Batch, QiskitRuntimeService
from qiskit_ibm_runtime import EstimatorV2 as Estimator
from qiskit_ibm_runtime import SamplerV2 as Sampler

import matplotlib.pyplot as plt
import numpy as np


from numpy import sqrt



print(f"Qiskit version: {qiskit.__version__}")




Qiskit version: 2.5.2


# 1 Basiswissen

In diesem Kapitel werden ein paar wichtige Grundlagen erklärt.

## 1.0 Bits versus Qubits

Bits können den Wert 0 oder 1 haben, ähnlich wie Münzen Kopf oder Zahl sein können.

Wenn Münzen flach auf dem Tisch liegen, ist die Wahrscheinlich für Kopf oder Zahl jeweils 100% oder 0%.

Wirft man die Münze in die Luft, ist die Wahrscheinlichkeit - solange sie in der Luft ist - irgendwas dazwischen.

Zum Beispiel: 30% Kopf und 70% Zahl

Als Vektor schreibt man das so:

In [10]:
bitVec = np.array([[0.3],[0.7]])

print("Wahrscheinlichkeitsvektor (30% Kopf und 70% Zahl): ")
print(bitVec)

#print("Der gleiche Wahrscheinlichkeitsvektor in ""Latex"" Format:")

#display(array_to_latex(bitVec))


Wahrscheinlichkeitsvektor (30% Kopf und 70% Zahl): 
[[0.3]
 [0.7]]


Für einen Wahrscheinlichkeitsvektor muss festgelegt werden, was oben (als erstes) und was unten (als zweites) steht.

In unserem Beispiel steht oben die Wahrscheinlich für Kopf und unten die Wahrscheinlich für Zahl.

Wichtig: Damit es ein gültiger Wahrscheinlichkeitsvektor ist, muss er aus zwei reelen Zahlen zwischen 0 und 1 bestehen, die in Summe 1 ergeben.

In [4]:
print("Wahrscheinlichkeit Kopf: ",bitVec[0])
print("Wahrscheinlichkeit Zahl: ",bitVec[1])
print("Summe: ",bitVec[0]+bitVec[1])


Wahrscheinlichkeit Kopf:  [0.3]
Wahrscheinlichkeit Zahl:  [0.7]
Summe:  [1.]


Für Wahrscheinlichkeitsvektoren von Bits ist die allgemeine Festlegung, dass oben die Wahrscheinlichkeit von 0 und unten die Wahrscheinlichkeit von 1 steht.

In [9]:
bitZero = np.array([[1],[0]])
bitOne = np.array([[0],[1]])

print("Wahrscheinlichkeitsvektor für 100% Wert 0 (und 0% Wert 1): ")
print(bitZero)
#display(array_to_latex(bitZero))
print("Wahrscheinlichkeitsvektor für 100% Wert 1 (und 0% Wert 0): ")
print(bitOne)
#display(array_to_latex(bitOne))

Wahrscheinlichkeitsvektor für 100% Wert 0 (und 0% Wert 1): 
[[1]
 [0]]
Wahrscheinlichkeitsvektor für 100% Wert 1 (und 0% Wert 0): 
[[0]
 [1]]


## 1.2 Zustandsvektoren von Qubits

Qubits lassen ähnlich wie Bits als Vektor mit zwei Zahlen schreiben.

Es gibt jedoch zwei Hauptunterschiede:



1.   Der Vektor kann imaginäre Zahlen enthalten und nicht nur reele Zahlen
2.   Um die Wahrscheinlichkeiten zu bestimmt müssen die Zahlen quadriert werden.


Wie bei einem Wahrscheinlichkeitsvektor eines Bit, muss bei einen Qubit Zustandsvektor die Summe der beiden Wahrscheinlichkeiten 1 ergeben.


In [15]:
zero = Statevector([1,0])
one = Statevector([0,1])

print("Vektor für 100% Zustand 0 (und 0% Wert 1): ")
display(zero.draw("text"))
print("Vektor für 100% Zustand 1 (und 0% Wert 0): ")
display(one.draw("text"))


Vektor für 100% Zustand 0 (und 0% Wert 1): 


[1.+0.j,0.+0.j]

Vektor für 100% Zustand 1 (und 0% Wert 0): 


[0.+0.j,1.+0.j]

Um zu prüfen, ob ein gültiger Qubit Zustandsvektor definiert wurde, müssen die zwei Zahlen quadriert und danach addiert werden. Das Ergebnis muss dann 1 ergeben.


Die Prüfung kann mit Hilfe der folgenden Funktion durchgeführt werden:

In [12]:
display(zero.is_valid())
display(one.is_valid())

True

True

Beispiele für weitere gültige Qubit Zustandsvektoren sind die folgenden Vektoren:

In [27]:

u = Statevector([sqrt(2)/2, sqrt(2)/2])
v = Statevector([(1/3 + 2/3j), -2 / 3])
w = Statevector([(3/5), (4/5)])

print("Qubit_u =")
display(u.draw("text"))
print("Qubit_v =")
display(v.draw("text"))
print("Qubit_w =")
display(w.draw("text"))


Qubit_u =


[0.70710678+0.j,0.70710678+0.j]

Qubit_v =


[ 0.33333333-0.66666667j,-0.66666667+0.j        ]

Qubit_w =


[0.6+0.j,0.8+0.j]

In [25]:

print("Qubit_u gültig: ")
display(w.is_valid())
print("Qubit_v gültig: ")
display(v.is_valid())
print("Qubit_w gültig: ")
display(w.is_valid())

Qubit_u gültig: 


True

Qubit_v gültig: 


True

Qubit_w gültig: 


True

Um Qubit Zustandsvektoren einfacher darzustellen, wird auch die folgende Schreibweise verwendet:

In [28]:


print("Andere Schreibweise für 100% Zudstand 0: ")
display(zero.draw("latex"))
print("Andere Schreibweise für 100% Zustand 1: ")
display(one.draw("latex"))

print("Andere Schreibweise für Qubit_u: ")
display(u.draw("latex"))
print("Andere Schreibweise für Qubit_v: ")
display(v.draw("latex"))
print("Andere Schreibweise für Qubit_w: ")
display(w.draw("latex"))





Andere Schreibweise für 100% Zudstand 0: 


<IPython.core.display.Latex object>

Andere Schreibweise für 100% Zustand 1: 


<IPython.core.display.Latex object>

Andere Schreibweise für Qubit_u: 


<IPython.core.display.Latex object>

Andere Schreibweise für Qubit_v: 


<IPython.core.display.Latex object>

Andere Schreibweise für Qubit_w: 


<IPython.core.display.Latex object>